---
- name: Install Apache Cassandra OSS from tarball
  hosts: all
  become: yes
  vars:
    cassandra_version: "4.1.10"
    oss_tarball: "./apache-cassandra-4.1.10-bin.tar.gz"  # Replace with your actual tarball path
    cassandra_user: cassandra
    cassandra_group: cassandra
    cassandra_install_dir: /opt/cassandra
    cassandra_data_dir: /var/lib/cassandra
    cassandra_log_dir: /var/log/cassandra
    logback_xml: "{{ cassandra_install_dir }}/conf/logback.xml"

  tasks:
    - name: Install required packages
      apt:
        name:
          - openjdk-11-jdk
          - sysstat
          - dstat
          - tar
          - curl
        state: present
        update_cache: yes

    - name: Create cassandra user and group
      ansible.builtin.user:
        name: "{{ cassandra_user }}"
        group: "{{ cassandra_group }}"
        system: yes
        shell: /usr/sbin/nologin
      ignore_errors: true

    - name: Create installation, data, and log directories
      file:
        path: "{{ item }}"
        state: directory
        owner: "{{ cassandra_user }}"
        group: "{{ cassandra_group }}"
        mode: '0777'
      loop:
        - "{{ cassandra_install_dir }}"
        - "{{ cassandra_data_dir }}"
        - "{{ cassandra_log_dir }}"

    - name: Copy OSS tarball to remote host
      copy:
        src: "{{ oss_tarball }}"
        dest: /tmp/oss.tar.gz
        mode: '0644'

    - name: Extract OSS tarball 
      unarchive:
        src: /tmp/oss.tar.gz
        dest: "{{ cassandra_install_dir }}"
        remote_src: yes
        extra_opts: [--strip-components=1]

    - name: Set ownership for installation directory
      file:
        path: "{{ cassandra_install_dir }}"
        owner: "{{ cassandra_user }}"
        group: "{{ cassandra_group }}"
        recurse: yes

    - name: Set ownership for installation directory
      file:
        path: "{{ cassandra_install_dir }}"
        owner: "{{ cassandra_user }}"
        group: "{{ cassandra_group }}"
        recurse: yes

    - name: Set logging locations in logback.xml
      replace:
        path: "{{ logback_xml }}"
        regexp: '\${cassandra\.logdir}'
        replace: "{{ cassandra_log_dir }}"

- name: Start up Cassandra process on the VMs
  hosts: all
  serial: 1
  vars:
    cassandra_install_dir: /opt/cassandra
    ansible_remote_tmp: /tmp/.ansible/tmp
    ansible_become_flags: "-n"
  tasks:
    - name: Stop existing Cassandra process (if running)
      become: yes
      become_user: cassandra
      shell: "pkill -u cassandra -f CassandraDaemon || true"
      ignore_errors: yes

    - name: Start Cassandra using su as cassandra user
      become: yes
      shell: "su -s /bin/bash -c '{{ cassandra_install_dir }}/bin/cassandra -R' cassandra"

