
---
- name: Stop Cassandra and install HCD with Java 11 setup
  hosts: all
  serial: 1
  become: yes
  vars:
    hcd_tarball: "./hcd-1.2.3-bin.tar.gz"  # Replace with your actual tarball path
    hcd_install_dir: "/opt/hcd"
    cassandra_data_dir: "/var/lib/cassandra"
    cassandra_log_dir: "/var/log/cassandra"
    java_package: "openjdk-11-jdk"
    cassandra_yaml: "/opt/hcd/resources/cassandra/conf/cassandra.yaml"
    jvm_options_file: "/opt/hcd/resources/cassandra/conf/jvm11-server.options"
  handlers:
    - name: Restart HCD
      shell: "{{ hcd_install_dir }}/bin/hcd cassandra &"
      async: 30
      poll: 0
  tasks:
    - name: Stop existing Cassandra process (if running)
      shell: "pkill -f CassandraDaemon || true"
      ignore_errors: yes

    - name: Install OpenJDK 11
      apt:
        name: "{{ java_package }}"
        state: present
        update_cache: yes

    - name: Set Java 11 as default using update-alternatives
      shell: |
        update-alternatives --install /usr/bin/java java /usr/lib/jvm/java-11-openjdk-amd64/bin/java 1
        update-alternatives --set java /usr/lib/jvm/java-11-openjdk-amd64/bin/java

    - name: Verify Java version
      command: java -version
      register: java_version_output
      changed_when: false

    - name: Show Java version
      debug:
        var: java_version_output.stderr_lines

    - name: Install archive tools (bzip2, xz-utils, unzip)
      apt:
        name:
          - bzip2
          - xz-utils
          - unzip
        state: present
        update_cache: yes

    - name: Ensure remote HCD directory exists
      file:
        path: "{{ hcd_install_dir }}"
        state: directory

    - name: Copy HCD tarball to remote host
      copy:
        src: "{{ hcd_tarball }}"
        dest: /tmp/hcd.tar.gz
        mode: '0644'

    - name: Extract HCD tarball to /opt/hcd
      unarchive:
        src: /tmp/hcd.tar.gz
        dest: "{{ hcd_install_dir }}"
        remote_src: yes
        extra_opts: [--strip-components=1]

    - name: Ensure logs directory exists
      file:
        path: "{{ cassandra_log_dir }}"
        state: directory
        mode: "0755"

    - name: Ensure /var/lib/cassandra exists and is writable
      file:
        path: "{{ cassandra_data_dir }}"
        state: directory
        mode: "0755"

    - name: Ensure /var/log/cassandra exists and is writable
      file:
        path: "{{ cassandra_log_dir }}"
        state: directory
        mode: "0755"

    - name: Set Java heap size to 31G in jvm11-server.options
      lineinfile:
        path: "{{ jvm_options_file }}"
        regexp: '^-Xmx'
        line: "-Xmx31G"
        backrefs: yes
      notify: Restart HCD

    - name: Set num_tokens to 8 in cassandra.yaml
      lineinfile:
        path: "{{ cassandra_yaml }}"
        regexp: '^num_tokens:'
        line: 'num_tokens: 8'
        backrefs: yes
      notify: Restart HCD

    - name: Set concurrent_compactors to 16 in cassandra.yaml
      lineinfile:
        path: "{{ cassandra_yaml }}"
        regexp: '^#?concurrent_compactors:.*'
        line: 'concurrent_compactors: 16'
        backrefs: yes
      notify: Restart HCD
